public enum Genre {
    ROCK,
    POP,
    JAZZ,
    CLASSICAL,
    HIP_HOP,
    ELECTRONIC,
    AUDIOBOOK_FICTION,
    AUDIOBOOK_NONFICTION,
    PODCAST_TECH,
    PODCAST_EDUCATION,
    PODCAST_ENTERTAINMENT,
    MIXED
}
